services:
  backend:
    image: v-validator-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - v-assure-network

  frontend:
    image: v-validator-frontend:latest
    ports:
      - "80:8080"
    depends_on:
      - backend
    networks:
      - v-assure-network

networks:
  v-assure-network:
    driver: bridge